# Usa una imagen base con Node.js
FROM node:17.9.1-alpine

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos de tu aplicación al contenedor
COPY . .

# Instala las dependencias
RUN npm install

# Expone el puerto en el que la aplicación de React se ejecutará
EXPOSE 3000

# Comando para iniciar la aplicación cuando el contenedor se inicia
CMD ["npm", "start"]