# Generated by Django 4.2.7 on 2023-11-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("id_comment", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comment",
                "db_table": "comment",
                "ordering": ["user"],
            },
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_name", models.CharField(max_length=100)),
                ("material", models.CharField(max_length=100)),
                ("start_date", models.CharField(max_length=15)),
                ("end_date", models.CharField(max_length=15)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="reports.comment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Query",
                "verbose_name_plural": "Areas de la empresa",
                "db_table": "query",
                "ordering": ["material"],
            },
        ),
    ]
