# Generated by Django 4.2.7 on 2023-11-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="id_comment",
            new_name="comment",
        ),
        migrations.RemoveField(
            model_name="query",
            name="comment",
        ),
        migrations.AddField(
            model_name="query",
            name="commentid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="reports.comment",
            ),
        ),
    ]
