# Generated by Django 4.2.7 on 2023-11-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_rename_id_comment_comment_comment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="query",
            options={"ordering": ["material"], "verbose_name": "Query"},
        ),
        migrations.AlterModelTable(
            name="comment",
            table="commentquery",
        ),
    ]
