# Generated by Django 4.2.7 on 2023-11-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_alter_query_options_alter_comment_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="description",
        ),
    ]
