# Generated by Django 4.2.7 on 2023-11-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_rename_comment_comment_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
