# Generated by Django 4.2.7 on 2023-11-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_comment_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="title",
        ),
        migrations.AlterField(
            model_name="query",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="query",
            name="start_date",
            field=models.DateField(),
        ),
    ]
